#!/usr/bin/env sh
# Generate one *.subfolder.conf for a linuxserver/nginx (lsio) instance and
# write it into a running container's live proxy-confs directory, as PUID
# 1000 (matching the image's own file ownership) via `docker exec --user`,
# then validate and reload.
#
# A typical lsio nginx setup's homepage generator (e.g.
# configs/nginx-cont-init.d/10-generate-homepage.sh) derives both the
# label and the link href from this filename, not the conf's own location
# block -- so <name> here becomes both the URL path (/<name>/) and the
# file name (<name>.subfolder.conf). Keep them the same thing.
#
# Usage:
#   add-subfolder-conf.sh <name> <upstream-host:port> [options]
#
# Options:
#   --mode strip|keep   strip (default): rewrite /<name>/x -> /x before
#                       forwarding, for an app that expects to be served
#                       at the site root (most apps: gitea, ollama, pi-web).
#                       keep: forward /<name>/x unchanged, for an app that
#                       strips its own configured prefix internally (e.g.
#                       dsh --base-path).
#   --container NAME    nginx container name (default: nginx)
#   --uid UID           uid to write the file as (default: 1000)
#   --no-allowlist      omit the shared allowlist.conf include
#
# Examples:
#   add-subfolder-conf.sh pi 127.0.0.1:8504
#   add-subfolder-conf.sh dsh 127.0.0.1:3080 --mode keep

set -eu

usage() {
  echo "usage: $0 <name> <upstream-host:port> [--mode strip|keep] [--container NAME] [--uid UID] [--no-allowlist]" >&2
  exit 1
}

[ $# -ge 2 ] || usage
NAME=$1
UPSTREAM=$2
shift 2

MODE=strip
CONTAINER=nginx
CONTAINER_UID=1000
ALLOWLIST_LINE="    include /config/nginx/proxy-confs/allowlist.conf;"

while [ $# -gt 0 ]; do
  case "$1" in
    --mode) MODE=$2; shift 2 ;;
    --container) CONTAINER=$2; shift 2 ;;
    --uid) CONTAINER_UID=$2; shift 2 ;;
    --no-allowlist) ALLOWLIST_LINE=""; shift ;;
    *) usage ;;
  esac
done

case "$MODE" in
  strip | keep) ;;
  *)
    echo "$0: --mode must be 'strip' or 'keep', got '$MODE'" >&2
    exit 1
    ;;
esac
case "$NAME" in
  */* | "")
    echo "$0: <name> must be one bare path segment, got '$NAME'" >&2
    exit 1
    ;;
esac

# Single-quoted printf formats keep nginx's own $variables ($scheme, $host,
# $1, $http_host) completely untouched by this shell; only the %s slots
# below are ours to fill.
if [ "$MODE" = strip ]; then
  PROXY_LINES=$(printf '    rewrite ^/%s/(.*)$ /$1 break;\n    proxy_pass http://%s;' "$NAME" "$UPSTREAM")
else
  PROXY_LINES=$(printf '    proxy_set_header Host $http_host;\n    proxy_pass http://%s;' "$UPSTREAM")
fi

CONF=$(printf '## Generated by docker/setup/lsio-nginx/%s -- edit the
## generator invocation, not this file, if you need to change it.
location = /%s {
    return 301 $scheme://$host/%s/;
}

location ^~ /%s/ {
%s
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

%s
}
' "$(basename "$0")" "$NAME" "$NAME" "$NAME" "$ALLOWLIST_LINE" "$PROXY_LINES")

TARGET_FILE="/config/nginx/proxy-confs/$NAME.subfolder.conf"

echo "Writing $TARGET_FILE in container '$CONTAINER' as uid $CONTAINER_UID..."
printf '%s\n' "$CONF" | docker exec --user "$CONTAINER_UID" -i "$CONTAINER" sh -c "cat > $TARGET_FILE"

echo "Validating nginx config..."
docker exec "$CONTAINER" nginx -t

echo "Reloading nginx..."
docker exec "$CONTAINER" nginx -s reload

echo "Regenerating the homepage index (if this setup has one)..."
docker exec "$CONTAINER" bash /custom-cont-init.d/10-generate-homepage.sh >/dev/null 2>&1 || true

echo "Done: $TARGET_FILE -> http://<host>/$NAME/"
